.DEFAULT_GOAL := help
.PHONY: help run

help: ## show this help
	@egrep -h '\s##\s' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[33m%-20s\033[0m %s\n", $$1, $$2}'

run: ## Run the local development container through docker-compose
	docker-compose up --build
