version: "3.4"
services:
  client:
    stdin_open: true
    container_name: client
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "./client/.next/:/app/.next/"
      - "./client/node_modules/:/app/node_modules/"
      - "./client:/app"
      # - "/app/.next"
      # - "/app/node_modules"

  server:
    build:
      context: ./server
      target: develop
    ports:
      - "9090:9090"
    volumes:
      - /code/node_modules
