version: "3.8"
services:
  client:
    stdin_open: true
    container_name: client
    build:
      context: ./client
      target: develop
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - mongo

  server:
    container_name: server
    build:
      context: ./server
      target: develop
    ports:
      - "9090:9090"
      - "9229:9229"
    volumes:
      - ./server:/code
      - /code/node_modules
    depends_on:
      - mongo
    # command: debug

  mongo:
    container_name: mongo
    image: mongo:4
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./.docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: app_db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
