[build]
  base = "client/"
  publish = "out/"
  command = "npm ci && npm run export"
[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://mackbellemore-mackbellemore-soen-390-team07.zeet.app"
[context.develop.environment]
  NEXT_PUBLIC_API_URL = "https://mackbellemore-mackbellemore-soen-390-team07-develop.zeet.app"
[context.deploy-preview.environment]
  NEXT_PUBLIC_API_URL = "https://mackbellemore-mackbellemore-soen-390-team07-develop.zeet.app"
[[redirects]]
  from = "/*"
  to = "/:splat"
