[build]
  base = "client/"
  publish = "out/"
  command = "npm i && npm run export"
[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://mackbellemore-mackbellemore-soen-390-team07.zeet.app"
  NODE_ENV = "development"
[context.develop.environment]
  NEXT_PUBLIC_API_URL = "https://mackbellemore-mackbellemore-soen-390-team07-develop.zeet.app"
  NODE_ENV = "development"
[context.deploy-preview.environment]
  NEXT_PUBLIC_API_URL = "https://mackbellemore-mackbellemore-soen-390-team07-develop.zeet.app"
  NODE_ENV = "development"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
