#!/bin/sh
. "$(dirname $0)/_/husky.sh"

format() {
  FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.js" "*.ts" "*.jsx" "*.json" | sed 's| |\\ |g')
  [ -z "$FILES" ] && return

  # Prettify all selected files
  echo "$FILES" | xargs ./client/node_modules/.bin/prettier --ignore-path .gitignore --write

  # Add back the modified/prettified files to staging
  echo "$FILES" | xargs git add
}

format
