name: Build

on:
  push:
    branches-ignore:
      - "main"
      - "develop"
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: ["client", "server"]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Install dependencies
        working-directory: ${{ matrix.project }}
        run: npm i

      - name: Build project
        working-directory: ${{ matrix.project }}
        run: npm run build
