name: Linting

on:
  push:
    branches-ignore:
      - "main"
      - "develop"
  pull_request:
    types: [opened, reopened]

jobs:
  linting:
    name: Run linters
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ["client", "server"]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Install Node.js dependencies
        working-directory: ${{ matrix.project }}
        run: npm install

      - name: Run Prettier
        working-directory: ${{ matrix.project }}
        run: npm run format:ci

      - name: Run ESLint
        working-directory: ${{ matrix.project }}
        run: npm run lint:ci
