name: Tests

on:
  push:
    branches-ignore:
      - "main"
      - "develop"
  pull_request:
    types: [opened, reopened]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ["server"]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Bring up containers
        working-directory: ${{ matrix.project }}
        run: docker-compose up -d server

      - name: Run unit tests with coverage
        working-directory: ${{ matrix.project }}
        run: docker-compose run server test:ci

      - name: Run integration tests
        working-directory: ${{ matrix.project }}
        run: docker-compose run server test:int
