name: Tests

on:
  push:
    branches-ignore:
      - "main"
      - "develop"
  pull_request:

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ["server"]

    steps:
      - uses: actions/checkout@v2

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.0

      - name: Running server tests
        env:
          MONGO_HOST: localhost
        working-directory: ${{ matrix.project }}
        run: docker build -t server . && docker run server "test:func"
