name: Tests

on:
  push:
    branches-ignore:
      - "main"
      - "develop"
  pull_request:

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ["server"]
    services:
      mongo:
        image: mongo:3.4.23
        ports:
          - 27017:27017
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
    steps:
      - uses: actions/checkout@v2

      - name: Running server tests
        working-directory: ${{ matrix.project }}
        run: docker build -t server . && docker run server "test:func"
