name: Tests

on:
  push:
    branches-ignore:
      - "main"
      - "develop"
  pull_request:

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ["server"]

    steps:
      - uses: actions/checkout@v2

      - name: Running server tests
        working-directory: ${{ matrix.project }}
        run: docker build -t server . && docker run server "test:ci"
